apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  labels:
    app: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
      - name: manager-notification
      #TODO change image tag
        image: felipegiusti/manager-notification:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: notification-configmap
        - secretRef:
            name: notification-secret