apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
spec:
  image: rabbitmq:3-management
  replicas: 1
  resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 800m
        memory: 1Gi
  rabbitmq:
    additionalConfig: |
      default_user=guest
      default_pass=guest